// State/controller integration tests in a minimal DOM fixture. These are not browser layout tests.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function app({initial={},blocked=false,quota=false,date='2026-10-07T13:00:00Z'}={}){
 const data=new Map(Object.entries(initial)),els=new Map(),tools=new Map(),listeners=new Map(),docListeners=new Map();let currentDate=date;
 const ids=[...fs.readFileSync(__dirname+'/../dist/index.html','utf8').matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
 function element(id){if(!els.has(id)){const classes=new Set();els.set(id,{id,innerHTML:'',textContent:'',value:'',hidden:false,open:false,elements:[],attributes:{},classList:{toggle(n,v){if(v===undefined)v=!classes.has(n);v?classes.add(n):classes.delete(n);},contains:n=>classes.has(n)},setAttribute(k,v){this.attributes[k]=v;},focus(){this.focused=true;},animate(){},scrollIntoView(){},querySelector(s){return element(id+':'+s);},showModal(){this.open=true;},close(){this.open=false;},getBoundingClientRect(){return{left:0,right:500,top:0,bottom:500};}});}return els.get(id);}
 ids.forEach(element);
 function byId(id){if(!ids.includes(id)&&id!=='solution')throw Error('Missing HTML id '+id);return element(id);}
 class Clock extends Date{constructor(...a){super(...(a.length?a:[currentDate]));}static now(){return new Date(currentDate).getTime();}}
 const context=vm.createContext({console,Intl,Date:Clock,setInterval(){},window:{scrollTo(){},matchMedia:()=>({matches:true}),addEventListener:(name,fn)=>listeners.set(name,fn)},document:{getElementById:byId,body:element('body'),hidden:false,addEventListener:(name,fn)=>docListeners.set(name,fn),modelContext:{registerTool:t=>tools.set(t.name,t)}},localStorage:{getItem(k){if(blocked)throw Error('blocked');return data.get(k)??null;},setItem(k,v){if(blocked||quota)throw Error('quota');data.set(k,v);}}});
 for(const f of ['engine','state','app'])vm.runInContext(fs.readFileSync(__dirname+'/../dist/'+f+'.js','utf8'),context);
 return{run:s=>vm.runInContext(s,context),el:element,data,tools,listeners,setDate:d=>currentDate=d};
}
test('UI starts; clue boundaries and rereads charge correctly',()=>{const a=app();assert.ok(a.el('title').textContent);a.el('prev-clue').onclick();assert.equal(a.run('state.clue'),0);a.el('next-clue').onclick();assert.equal(a.run('currentScore()'),94);a.el('prev-clue').onclick();assert.equal(a.run('currentScore()'),94);for(let i=0;i<20;i++)a.el('next-clue').onclick();assert.equal(a.run('state.clue'),7);assert.equal(a.run('currentScore()'),58);assert.equal(a.el('next-clue').disabled,true);});
test('invalid answer free; duplicate wrong submission free; score persisted',()=>{const a=app();assert.ok(a.run('accuse({})').error);assert.equal(a.run('state.attempts'),0);a.run("var wrong={...c.answer,killer:c.suspects.find(p=>p.id!==c.answer.killer).id};accuse(wrong)");assert.equal(a.run('state.attempts'),1);assert.equal(a.run('accuse(wrong).duplicate'),true);a.run('load()');assert.equal(a.run('accuse(wrong).duplicate'),true);assert.equal(a.run('currentScore()'),85);});
test('solve, browse remaining clues, reload: completion and original score retained',()=>{const a=app();a.el('next-clue').onclick();a.run('accuse({...c.answer})');assert.equal(a.run('state.solved'),true);const score=a.run('currentScore()');for(let i=0;i<8;i++)a.el('next-clue').onclick();a.run('load()');assert.equal(a.run('state.solved'),true);assert.equal(a.run('currentScore()'),score);assert.equal(a.run('state.finalClues'),2);});
test('mode saves isolated and notes survive changing modes',()=>{const a=app();a.el('notes').oninput({target:{value:'ನನ್ನ ಸಾಕ್ಷ್ಯ'}});a.el('next-clue').onclick();a.el('hard').onclick();assert.equal(a.run('state.notes'),'');a.el('easy').onclick();assert.equal(a.run('state.notes'),'ನನ್ನ ಸಾಕ್ಷ್ಯ');assert.equal(a.run('state.highest'),1);});
test('blocked storage and quota preserve progress in memory during navigation',()=>{for(const options of [{blocked:true},{quota:true}]){const a=app(options);a.el('notes').oninput({target:{value:'ಉಳಿಸದ ಟಿಪ್ಪಣಿ'}});a.el('next-clue').onclick();a.el('hard').onclick();a.el('easy').onclick();assert.equal(a.run('state.notes'),'ಉಳಿಸದ ಟಿಪ್ಪಣಿ');assert.equal(a.run('state.highest'),1);assert.equal(a.run('storageAvailable'),false);}});
test('malformed JSON does not crash startup',()=>{const a=app({initial:{'rahasya-v1:2026-10-07:easy':'{broken'}});assert.equal(a.run('state.clue'),0);assert.ok(a.el('title').textContent);a.el('next-clue').onclick();assert.equal(a.run('state.clue'),1);});
test('conflicting marks warned, clearing requires confirmation and preserves text',()=>{const a=app();a.run("state.marks={[person+'-0-0']:1,[person+'-1-0']:1};state.notes='ಸಾಕ್ಷ್ಯ';renderBoard()");assert.equal(a.el('board-warning').hidden,false);a.el('clear-notes').onclick();assert.equal(a.el('modal').open,true);assert.equal(a.run('Object.keys(state.marks).length'),2);a.el('modal-body').onclick({target:{id:'confirm-clear',closest:()=>null}});assert.equal(a.run('Object.keys(state.marks).length'),0);assert.equal(a.run('state.notes'),'ಸಾಕ್ಷ್ಯ');});
test('two-tab conflicts do not overwrite remote progress, reload resolves them',()=>{const a=app();a.el('notes').oninput({target:{value:'local'}});a.data.set(a.run('storageKey()'),JSON.stringify({notes:'remote',clue:2,highest:2,attempts:0}));a.listeners.get('storage')({key:a.run('storageKey()')});assert.equal(a.el('sync-notice').hidden,false);a.el('next-clue').onclick();assert.equal(a.run('state.clue'),0);assert.match(a.data.get(a.run('storageKey()')),/remote/);a.el('reload-progress').onclick();assert.equal(a.run('state.notes'),'remote');assert.equal(a.el('sync-notice').hidden,true);});
test('midnight announces new case without discarding current notes',()=>{const a=app();a.el('notes').oninput({target:{value:'ಇಂದಿನ ಟಿಪ್ಪಣಿ'}});a.setDate('2026-10-07T18:30:00Z');a.run('checkDay()');assert.equal(a.el('day-notice').hidden,false);assert.equal(a.run('key'),'2026-10-07');a.el('open-today').onclick();assert.equal(a.run('key'),'2026-10-08');assert.equal(a.run('state.notes'),'');assert.match(a.data.get('rahasya-v1:2026-10-07:easy'),/ಇಂದಿನ/);});
test('archive selection, theme toggle and keyboard tabs',()=>{const a=app();a.el('archive').onclick();assert.equal((a.el('modal-body').innerHTML.match(/data-day=/g)||[]).length,7);a.el('modal-body').onclick({target:{id:'',closest:()=>({dataset:{day:'2026-10-06'}})}});assert.equal(a.run('key'),'2026-10-06');assert.equal(a.el('modal').open,false);a.el('theme').onclick();assert.equal(a.data.get('rahasya-theme'),'light');const p=a.run('person');a.el('person-tabs').onkeydown({key:'ArrowRight',preventDefault(){}});assert.notEqual(a.run('person'),p);});
test('WebMCP uses same actions and rejects invalid input in fixture',()=>{const a=app();assert.deepEqual([...a.tools.keys()],['read_current_case','reveal_next_clue','submit_accusation']);const read=a.tools.get('read_current_case');assert.equal(read.annotations.readOnlyHint,true);assert.equal(read.execute().clues.length,1);a.tools.get('reveal_next_clue').execute({});assert.equal(a.run('state.highest'),1);assert.throws(()=>a.tools.get('submit_accusation').execute({killer:'9',weapon:'0',time:'19:30'}));assert.equal(a.run('state.attempts'),0);a.tools.get('submit_accusation').execute(a.run('({...c.answer})'));assert.equal(a.run('state.solved'),true);});
